#! /bin/sh

# Wallpaper
feh --bg-fill --randomize ~/Pictures/Wallpapers/* &

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch &

# Compositor
killall picom
picom --experimental-backends &

bspc monitor DisplayPort-0 -d 1 2 3 4 
bspc monitor DisplayPort-2 -d 5 6 7 8
bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a alacritty desktop='^1'
bspc rule -a obs desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Color
bspc config normal_border_color   "#282c34"
bspc config focused_border_color  "#5c6370"
bspc config presel_feedback_color "#5c6370"

# Mouse
bspc config swallow_first_click true

