[package]
name = "blazingly-fast-python"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
factorial = "0.4.0"
num = "0.4.1"

[[bin]]
name = "blazingly-fast-python"
path = "main.rs"
